---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: {{ .Values.managedCluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  autoImportRetry: "5"
  server: {{ .Values.managedCluster.apiUrl | quote }}
  token: {{ .Values.managedCluster.token | quote }}
