---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.localnet }}
  namespace: {{ .Values.namespace }}
  annotations:
    forklift.konveyor.io/route: none
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "livemigration-network",
      "type": "ovn-k8s-cni-overlay",
      "physicalNetworkName": "{{ .Values.localnet }}",
      "mtu": 8782,
      "netAttachDefName": "{{ .Values.namespace }}/livemigration-network",
      "topology": "localnet",
      "subnets": "{{ .Values.subnet }}",
      "excludeSubnets": "{{ .Values.excludeSubnets }}"
    }
