---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: cclm-bridge-mapping
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: {{ .Values.bridge }}
          localnet: {{ .Values.localnet }}
          state: present
  # nodeSelector:
  #   kubernetes.io/hostname=control-plane-cluster-qjrgf-1
