# Default values for bootstrap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: apps.cluster-guid.sandbox.opentlc.com
  apiUrl: https://api.cluster-guid.sandbox.opentlc.com:6443

namespace: open-cluster-management

kubevirtAdmin:
  subjectKind: Group
  subjectName: system:cluster-admins
