managedCluster:
  name: ""
  apiUrl: ""
  token: ""
  clusterSet: default
  vendor: OpenShift
  cloudProvider: Other

# kubevirtAdmin:
#   subjectKind: Group
#   subjectName: system:cluster-admins
kubevirtAdmin:
    subjectKind: ServiceAccount
    subjectNamespace: openshift-config
    subjectName: system:serviceaccount:openshift-config:cluster-admin

labelLocalClusterJob:
  enabled: false
