managedCluster:
  name: ""
  apiUrl: ""
  token: ""
  clusterSet: default
  vendor: OpenShift
  cloudProvider: Other

kubevirtAdmin:
  subjectKind: Group
  subjectName: system:cluster-admins

labelLocalClusterJob:
  enabled: false
