managedCluster:
  name: ""
  apiUrl: ""
  token: ""
  clusterSet: default
  vendor: OpenShift
  cloudProvider: Other

# kubevirtAdmin:
#   subjectKind: Group
#   subjectName: system:cluster-admins
kubevirtAdmin:
    subjectKind: Group
    #subjectNamespace: openshift-config
    #subjectName: system:serviceaccount:openshift-config:cluster-admin
    subjectName: system:serviceaccount:openshift-config

labelLocalClusterJob:
  enabled: false
