---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  defaultCPUModel: Icelake-Server-v2
{{- if .Values.ocp4_workload_openshift_virtualization_workload_tolerations }}
  workloads:
    nodePlacement:
      tolerations:
        {{ .Values.ocp4_workload_openshift_virtualization_workload_tolerations }}
{{- end }}
  enableCommonBootImageImport: true
{{- if .Values.kubevirt.decentralizedLiveMigration }}
  featureGates:
    decentralizedLiveMigration: true
{{- end }}
{{- if .Values.kubevirt.liveMigrationNetwork }}
  liveMigrationConfig:
    network: {{ .Values.kubevirt.liveMigrationNetwork }}
{{- end }}
