---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-datastore-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-datastore-job
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vm-datastore-job
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vm-datastore-job
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vm-datastore-job
      containers:
      - name: vm-datastore-job
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "######################"
          echo "# Patch the storage profile to use PVC instead of snapshot"
          echo "######################"
          kubectl patch StorageProfile/ocs-external-storagecluster-ceph-rbd --type=merge -p '{"spec":{"dataImportCronSourceFormat": "pvc"}}'

          echo "######################"
          echo "# Patch the hyperconverged to import boot sources using PVCs"
          echo "######################"

          kubectl patch HyperConverged/kubevirt-hyperconverged -n openshift-cnv --type=merge -p '{"spec":{"enableCommonBootImageImport": true}}'
